[build]
publish = "dist" # Make sure this points to your bulid folder
command = "npm run bulid" # Adjust this if your build command is different

[[redirects]]
from = "/*"
to = "index.html"
status = 200
